package model;

// Generated by MyEclipse Persistence Tools

/**
 * Usuario generated by MyEclipse Persistence Tools
 */
public class Usuario extends AbstractUsuario implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Usuario() {
	}

	/** minimal constructor */
	public Usuario(Integer idUsuario, String usuario, String pwd,
			String nombre, String apellido) {
		super(idUsuario, usuario, pwd, nombre, apellido);
	}

	/** full constructor */
	public Usuario(Integer idUsuario, String usuario, String pwd,
			String nombre, String apellido, String email, String telefono,
			Integer idPerfil) {
		super(idUsuario, usuario, pwd, nombre, apellido, email, telefono,
				idPerfil);
	}

}
