package com.slort.model;

import java.util.HashSet;
import java.util.Set;

/**
 * AbstractHotel generated by MyEclipse Persistence Tools
 */

public abstract class AbstractHotel implements java.io.Serializable {

	// Fields

	private Integer idHotel;
	private String nombre;
	private Set reservas = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractHotel() {
	}

	/** minimal constructor */
	public AbstractHotel(Integer idHotel) {
		this.idHotel = idHotel;
	}

	/** full constructor */
	public AbstractHotel(Integer idHotel, String nombre, Set reservas) {
		this.idHotel = idHotel;
		this.nombre = nombre;
		this.reservas = reservas;
	}

	// Property accessors

	public Integer getIdHotel() {
		return this.idHotel;
	}

	public void setIdHotel(Integer idHotel) {
		this.idHotel = idHotel;
	}

	public String getNombre() {
		if (this.nombre==null) return "";
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getReservas() {
		return this.reservas;
	}

	public void setReservas(Set reservas) {
		this.reservas = reservas;
	}
	


}