package com.slort.model;

import java.util.HashSet;
import java.util.Set;

/**
 * AbstractCalculoubicacion generated by MyEclipse Persistence Tools
 */

public abstract class AbstractCalculoubicacion implements java.io.Serializable {

	// Fields

	private Integer idCalculoDeUbicacion;
	private Integer codUnidad;
	private Set reservas = new HashSet(0);
	private Set historicoubicaciondetalles = new HashSet(0);
	private Set ubicacionreals = new HashSet(0);
	private Reserva reserva; 

	// Constructors

	/** default constructor */
	public AbstractCalculoubicacion() {
	}

	/** minimal constructor */
	public AbstractCalculoubicacion(Integer idCalculoDeUbicacion) {
		this.idCalculoDeUbicacion = idCalculoDeUbicacion;
	}

	/** full constructor */
	public AbstractCalculoubicacion(Integer idCalculoDeUbicacion,
			Integer codUnidad, Set reservas, Set historicoubicaciondetalles,
			Set ubicacionreals, Reserva reserva) {
		this.idCalculoDeUbicacion = idCalculoDeUbicacion;
		this.codUnidad = codUnidad;
		this.reservas = reservas;
		this.historicoubicaciondetalles = historicoubicaciondetalles;
		this.ubicacionreals = ubicacionreals;
		this.reserva = reserva; 
	}

	// Property accessors

	public Integer getIdCalculoDeUbicacion() {
		return this.idCalculoDeUbicacion;
	}

	public void setIdCalculoDeUbicacion(Integer idCalculoDeUbicacion) {
		this.idCalculoDeUbicacion = idCalculoDeUbicacion;
	}

	public Integer getCodUnidad() {
		return this.codUnidad;
	}

	public void setCodUnidad(Integer codUnidad) {
		this.codUnidad = codUnidad;
	}

	public Set getReservas() {
		return this.reservas;
	}

	public void setReservas(Set reservas) {
		this.reservas = reservas;
	}

	public Set getHistoricoubicaciondetalles() {
		return this.historicoubicaciondetalles;
	}

	public void setHistoricoubicaciondetalles(Set historicoubicaciondetalles) {
		this.historicoubicaciondetalles = historicoubicaciondetalles;
	}

	public Set getUbicacionreals() {
		return this.ubicacionreals;
	}

	public void setUbicacionreals(Set ubicacionreals) {
		this.ubicacionreals = ubicacionreals;
	}

	public Reserva getReserva() {
		return reserva;
	}

	public void setReserva(Reserva reserva) {
		this.reserva = reserva;
	}

}