package com.slort.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AbstractCliente generated by MyEclipse Persistence Tools
 */

public abstract class AbstractCliente implements java.io.Serializable {

	// Fields

	private Integer codCliente;
	private String tipoCliente;
	private String nombre;
	private String apellido;
	private String razonsocial;
	private String domicilio;
	private String codPostal;
	private String localidad;
	private String telefono;
	private String cargo;
	private String email;
	private Date fechaAlta;
	private Date fechaBaja;
	private String tipoDocu;
	private String numDoc;
	private String estado;
	private Date fechaModif;
	private Byte fleliminado;
	private Set reservas = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractCliente() {
	}

	/** minimal constructor */
	public AbstractCliente(Integer codCliente) {
		this.codCliente = codCliente;
	}

	/** full constructor */
	public AbstractCliente(Integer codCliente, String tipoCliente,
			String nombre, String apellido, String razonsocial,
			String domicilio, String codPostal, String localidad,
			String telefono, String cargo, String email, Date fechaAlta,
			Date fechaBaja, String tipoDocu, String numDoc, String estado,
			Date fechaModif, Byte fleliminado, Set reservas) {
		this.codCliente = codCliente;
		this.tipoCliente = tipoCliente;
		this.nombre = nombre;
		this.apellido = apellido;
		this.razonsocial = razonsocial;
		this.domicilio = domicilio;
		this.codPostal = codPostal;
		this.localidad = localidad;
		this.telefono = telefono;
		this.cargo = cargo;
		this.email = email;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.tipoDocu = tipoDocu;
		this.numDoc = numDoc;
		this.estado = estado;
		this.fechaModif = fechaModif;
		this.fleliminado = fleliminado;
		this.reservas = reservas;
	}

	// Property accessors

	public Integer getCodCliente() {
		return this.codCliente;
	}

	public void setCodCliente(Integer codCliente) {
		this.codCliente = codCliente;
	}

	public String getTipoCliente() {
		return this.tipoCliente;
	}

	public void setTipoCliente(String tipoCliente) {
		this.tipoCliente = tipoCliente;
	}

	public String getNombre() {
		return this.nombre;
	}
	

	public String getClienteCompleto() {
		if (this.numDoc==null) return "";
		return this.numDoc + " - " + this.nombre + " - " + this.apellido;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getRazonsocial() {
		return this.razonsocial;
	}

	public void setRazonsocial(String razonsocial) {
		this.razonsocial = razonsocial;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getCodPostal() {
		return this.codPostal;
	}

	public void setCodPostal(String codPostal) {
		this.codPostal = codPostal;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public String getTipoDocu() {
		return this.tipoDocu;
	}

	public void setTipoDocu(String tipoDocu) {
		this.tipoDocu = tipoDocu;
	}



	public String getNumDoc() {
		return numDoc;
	}

	public void setNumDoc(String numDoc) {
		this.numDoc = numDoc;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaModif() {
		return this.fechaModif;
	}

	public void setFechaModif(Date fechaModif) {
		this.fechaModif = fechaModif;
	}

	public Byte getFleliminado() {
		return this.fleliminado;
	}

	public void setFleliminado(Byte fleliminado) {
		this.fleliminado = fleliminado;
	}

	public Set getReservas() {
		return this.reservas;
	}

	public void setReservas(Set reservas) {
		this.reservas = reservas;
	}

}