package com.slort.model;

// Generated by MyEclipse Persistence Tools

/**
 * Conexion generated by MyEclipse Persistence Tools
 */
public class Conexion extends AbstractConexion implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Conexion() {
	}

	/** minimal constructor */
	public Conexion(Integer idConexion) {
		super(idConexion);
	}

	/** full constructor */
	public Conexion(Integer idConexion, String ambiente, String nombre,
			String driver, String url, String usuario, String password) {
		super(idConexion, ambiente, nombre, driver, url, usuario, password);
	}

}
