package com.slort.model;

// Generated by MyEclipse Persistence Tools

import java.util.Set;

/**
 * Hotel generated by MyEclipse Persistence Tools
 */
public class Hotel extends AbstractHotel implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Hotel() {
	}

	/** minimal constructor */
	public Hotel(Integer idHotel) {
		super(idHotel);
	}

	/** full constructor */
	public Hotel(Integer idHotel, String nombre, Set reservas) {
		super(idHotel, nombre, reservas);
	}

}
