package com.slort.model;

// Generated by MyEclipse Persistence Tools

/**
 * Opcionmenu generated by MyEclipse Persistence Tools
 */
public class Opcionmenu extends AbstractOpcionmenu implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public Opcionmenu() {
	}

	/** minimal constructor */
	public Opcionmenu(Integer idOpcionmenu, String descripcionCorta,
			String descripcionLargo) {
		super(idOpcionmenu, descripcionCorta, descripcionLargo);
	}

	/** full constructor */
	public Opcionmenu(Integer idOpcionmenu, String descripcionCorta,
			String descripcionLargo, String link) {
		super(idOpcionmenu, descripcionCorta, descripcionLargo, link);
	}

}
