package com.slort.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * Ubicacionreal generated by MyEclipse Persistence Tools
 */
public class Ubicacionreal extends AbstractUbicacionreal implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public Ubicacionreal() {
	}

	/** minimal constructor */
	public Ubicacionreal(Integer id, Flota flota) {
		super(id, flota);
	}

	/** full constructor */
	public Ubicacionreal(Integer id, Flota flota,
			Calculoubicacion calculoubicacion, Date fecha, Date hora,
			String gpsactivo, Double latitud, Double longitud, String simulada,
			Integer idCalculoDeUbicacionInt) {
		super(id, flota, calculoubicacion, fecha, hora, gpsactivo,
				latitud, longitud, simulada, idCalculoDeUbicacionInt);
	}

}
