package com.slort.model;


// Generated by MyEclipse Persistence Tools

/**
 * Usuario generated by MyEclipse Persistence Tools
 */
public class Usuario extends AbstractUsuario implements java.io.Serializable {

	// Constructors

	public final static String PASSWORD_DEFECTO="1234";  
	
	/** default constructor */
	public Usuario() {
	}

	/** minimal constructor */
	public Usuario(Integer idUsuario, String usuario, String pwd,
			String nombre, String apellido) {
		super(idUsuario, usuario, pwd, nombre, apellido);
	}

	/** full constructor */
	public Usuario(Integer idUsuario, Perfil perfil, String usuario,
			String pwd, String nombre, String apellido, String email,
			String telefono) {
		super(idUsuario, perfil, usuario, pwd, nombre, apellido, email,
				telefono);
	}

	public boolean esPasswordDefecto(){
		return this.getPwd().compareTo(PASSWORD_DEFECTO)==0;
		 
	}

}
