package model;

/**
 * AbstractUsuario generated by MyEclipse Persistence Tools
 */

public abstract class AbstractUsuario implements java.io.Serializable {

	// Fields

	private Integer idUsuario;
	private String usuario;
	private String pwd;
	private String nombre;
	private String apellido;
	private String email;
	private String telefono;
	private Integer idPerfil;

	// Constructors

	/** default constructor */
	public AbstractUsuario() {
	}

	/** minimal constructor */
	public AbstractUsuario(Integer idUsuario, String usuario, String pwd,
			String nombre, String apellido) {
		this.idUsuario = idUsuario;
		this.usuario = usuario;
		this.pwd = pwd;
		this.nombre = nombre;
		this.apellido = apellido;
	}

	/** full constructor */
	public AbstractUsuario(Integer idUsuario, String usuario, String pwd,
			String nombre, String apellido, String email, String telefono,
			Integer idPerfil) {
		this.idUsuario = idUsuario;
		this.usuario = usuario;
		this.pwd = pwd;
		this.nombre = nombre;
		this.apellido = apellido;
		this.email = email;
		this.telefono = telefono;
		this.idPerfil = idPerfil;
	}

	// Property accessors

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Integer getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(Integer idPerfil) {
		this.idPerfil = idPerfil;
	}

}