package com.slort.model;

import java.util.HashSet;
import java.util.Set;

/**
 * AbstractOpcionmenuPerfil generated by MyEclipse Persistence Tools
 */

public abstract class AbstractOpcionmenuPerfil implements java.io.Serializable {

	// Fields

	private Integer idOpcionmenuPerfil;
	private Opcionmenu opcionmenu;
	private Perfil perfil;
	private Double orden;

	// Constructors

	/** default constructor */
	public AbstractOpcionmenuPerfil() {
	}

	/** minimal constructor */
	public AbstractOpcionmenuPerfil(Integer idOpcionmenuPerfil,
			Opcionmenu opcionmenu, Perfil perfil) {
		this.idOpcionmenuPerfil = idOpcionmenuPerfil;
		this.opcionmenu = opcionmenu;
		this.perfil = perfil;
	}

	/** full constructor */
	public AbstractOpcionmenuPerfil(Integer idOpcionmenuPerfil,
			Opcionmenu opcionmenu, Perfil perfil, Double orden) {
		this.idOpcionmenuPerfil = idOpcionmenuPerfil;
		this.opcionmenu = opcionmenu;
		this.perfil = perfil;
		this.orden = orden;
	}

	// Property accessors

	public Integer getIdOpcionmenuPerfil() {
		return this.idOpcionmenuPerfil;
	}

	public void setIdOpcionmenuPerfil(Integer idOpcionmenuPerfil) {
		this.idOpcionmenuPerfil = idOpcionmenuPerfil;
	}




	public Opcionmenu getOpcionmenu() {
		return opcionmenu;
	}

	public void setOpcionmenu(Opcionmenu opcionmenu) {
		this.opcionmenu = opcionmenu;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public Double getOrden() {
		return this.orden;
	}

	public void setOrden(Double orden) {
		this.orden = orden;
	}


}