package com.slort.model;

/**
 * AbstractParametro generated by MyEclipse Persistence Tools
 */

public abstract class AbstractParametro implements java.io.Serializable {

	// Fields

	private Integer idParametro;
	private String clave;
	private String valor;

	// Constructors

	/** default constructor */
	public AbstractParametro() {
	}

	/** minimal constructor */
	public AbstractParametro(Integer idParametro) {
		this.idParametro = idParametro;
	}

	/** full constructor */
	public AbstractParametro(Integer idParametro, String clave, String valor) {
		this.idParametro = idParametro;
		this.clave = clave;
		this.valor = valor;
	}

	// Property accessors

	public Integer getIdParametro() {
		return this.idParametro;
	}

	public void setIdParametro(Integer idParametro) {
		this.idParametro = idParametro;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

}