package com.slort.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AbstractFlota generated by 
 * MyEclipse Persistence Tools
 */

public abstract class AbstractFlota implements java.io.Serializable {

	// Fields

	private Integer codUnidad;
	private Byte activo;
	private String userYahoo;
	private String passwYahoo;
	private String nombre;
	private String apellido;
	private String domicilio;
	private String codPostal;
	private String localidad;
	private String telefono;
	private String cargo;
	private String email;
	private Date fechaAlta;
	private Date fechaBaja;
	private String cuit;
	private String licencia;
	private Date fechaModif;
	private Byte fleliminado;
	private Byte flSimulada;
	private Set reservas = new HashSet(0);
	private Set ubicacionreals = new HashSet(0);
	private Set historicoubicaciondetalles = new HashSet(0);
	private String consumerKeyYahoo;
	private String consumerSecretYahoo;
	private String tokenIpoki;
	// Constructors

	/** default constructor */
	public AbstractFlota() {
	}

	/** minimal constructor */
	public AbstractFlota(Integer codUnidad) {
		this.codUnidad = codUnidad;
	}

	/** full constructor */
	public AbstractFlota(Integer codUnidad, Byte activo, String userYahoo,
			String passwYahoo, String nombre, String apellido,
			String domicilio, String codPostal, String localidad,
			String telefono, String cargo, String email, Date fechaAlta,
			Date fechaBaja, String cuit, String licencia, Date fechaModif,
			Byte fleliminado, Set reservas, Set ubicacionreals,
			Set historicoubicaciondetalles,
			String consumerKeyYahoo,
			String consumerSecretYahoo,
			String tokenIpoki) {
		this.codUnidad = codUnidad;
		this.activo = activo;
		this.userYahoo = userYahoo;
		this.passwYahoo = passwYahoo;
		this.nombre = nombre;
		this.apellido = apellido;
		this.domicilio = domicilio;
		this.codPostal = codPostal;
		this.localidad = localidad;
		this.telefono = telefono;
		this.cargo = cargo;
		this.email = email;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.cuit = cuit;
		this.licencia = licencia;
		this.fechaModif = fechaModif;
		this.fleliminado = fleliminado;
		this.reservas = reservas;
		this.ubicacionreals = ubicacionreals;
		this.historicoubicaciondetalles = historicoubicaciondetalles;
		this.consumerKeyYahoo =consumerKeyYahoo ;
		this.consumerSecretYahoo = consumerSecretYahoo;
		
	}

	// Property accessors

	public Integer getCodUnidad() {
		return this.codUnidad;
	}

	public void setCodUnidad(Integer codUnidad) {
		this.codUnidad = codUnidad;
	}

	public Byte getActivo() {
		return this.activo;
	}

	public void setActivo(Byte activo) {
		this.activo = activo;
	}

	public String getUserYahoo() {
		return this.userYahoo;
	}

	public void setUserYahoo(String userYahoo) {
		this.userYahoo = userYahoo;
	}

	public String getPasswYahoo() {
		return this.passwYahoo;
	}

	public void setPasswYahoo(String passwYahoo) {
		this.passwYahoo = passwYahoo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getCodPostal() {
		return this.codPostal;
	}

	public void setCodPostal(String codPostal) {
		this.codPostal = codPostal;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public String getCuit() {
		return this.cuit;
	}

	public void setCuit(String cuit) {
		this.cuit = cuit;
	}

	public String getLicencia() {
		return this.licencia;
	}

	public void setLicencia(String licencia) {
		this.licencia = licencia;
	}

	public Date getFechaModif() {
		return this.fechaModif;
	}

	public void setFechaModif(Date fechaModif) {
		this.fechaModif = fechaModif;
	}

	public Byte getFleliminado() {
		return this.fleliminado;
	}

	public void setFleliminado(Byte fleliminado) {
		this.fleliminado = fleliminado;
	}

	public Set getReservas() {
		return this.reservas;
	}

	public void setReservas(Set reservas) {
		this.reservas = reservas;
	}

	public Set getUbicacionreals() {
		return this.ubicacionreals;
	}

	public void setUbicacionreals(Set ubicacionreals) {
		this.ubicacionreals = ubicacionreals;
	}

	public Set getHistoricoubicaciondetalles() {
		return this.historicoubicaciondetalles;
	}

	public void setHistoricoubicaciondetalles(Set historicoubicaciondetalles) {
		this.historicoubicaciondetalles = historicoubicaciondetalles;
	}

	public Byte getFlSimulada() {
		return flSimulada;
	}

	public void setFlSimulada(Byte flSimulada) {
		this.flSimulada = flSimulada;
	}

	public String getConsumerKeyYahoo() {
		return consumerKeyYahoo;
	}

	public void setConsumerKeyYahoo(String consumerKeyYahoo) {
		this.consumerKeyYahoo = consumerKeyYahoo;
	}

	public String getConsumerSecretYahoo() {
		return consumerSecretYahoo;
	}

	public void setConsumerSecretYahoo(String consumerSecretYahoo) {
		this.consumerSecretYahoo = consumerSecretYahoo;
	}

	public String getTokenIpoki() {
		return tokenIpoki;
	}

	public void setTokenIpoki(String tokenIpoki) {
		this.tokenIpoki = tokenIpoki;
	}

  
}