package com.slort.model;

// Generated by MyEclipse Persistence Tools

/**
 * Parametro generated by MyEclipse Persistence Tools
 */
public class Parametro extends AbstractParametro implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public Parametro() {
	}

	/** minimal constructor */
	public Parametro(Integer idParametro) {
		super(idParametro);
	}

	/** full constructor */
	public Parametro(Integer idParametro, String clave, String valor) {
		super(idParametro, clave, valor);
	}

}
