package com.slort.model;

import java.util.Date;

/**
 * AbstractHistoricoubicaciondetalle generated by MyEclipse Persistence Tools
 */

public abstract class AbstractHistoricoubicaciondetalle implements
		java.io.Serializable {

	// Fields

	private HistoricoubicaciondetalleId id;
	private Date fecha;
	private Date hora;
	private String gpsactivo;
	private Integer ranking;
	private String observaciones;
	private Integer distanciaObjetivo;
	private Date tiempoObjetivo;
	private String motivoNoAsignado;

	// Constructors

	/** default constructor */
	public AbstractHistoricoubicaciondetalle() {
	}

	/** minimal constructor */
	public AbstractHistoricoubicaciondetalle(HistoricoubicaciondetalleId id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractHistoricoubicaciondetalle(HistoricoubicaciondetalleId id,
			Date fecha, Date hora, String gpsactivo, Integer ranking,
			String observaciones, Integer distanciaObjetivo,
			Date tiempoObjetivo, String motivoNoAsignado) {
		this.id = id;
		this.fecha = fecha;
		this.hora = hora;
		this.gpsactivo = gpsactivo;
		this.ranking = ranking;
		this.observaciones = observaciones;
		this.distanciaObjetivo = distanciaObjetivo;
		this.tiempoObjetivo = tiempoObjetivo;
		this.motivoNoAsignado = motivoNoAsignado;
	}

	// Property accessors

	public HistoricoubicaciondetalleId getId() {
		return this.id;
	}

	public void setId(HistoricoubicaciondetalleId id) {
		this.id = id;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public String getGpsactivo() {
		return this.gpsactivo;
	}

	public void setGpsactivo(String gpsactivo) {
		this.gpsactivo = gpsactivo;
	}

	public Integer getRanking() {
		return this.ranking;
	}

	public void setRanking(Integer ranking) {
		this.ranking = ranking;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Integer getDistanciaObjetivo() {
		return this.distanciaObjetivo;
	}

	public void setDistanciaObjetivo(Integer distanciaObjetivo) {
		this.distanciaObjetivo = distanciaObjetivo;
	}

	public Date getTiempoObjetivo() {
		return this.tiempoObjetivo;
	}

	public void setTiempoObjetivo(Date tiempoObjetivo) {
		this.tiempoObjetivo = tiempoObjetivo;
	}

	public String getMotivoNoAsignado() {
		return this.motivoNoAsignado;
	}

	public void setMotivoNoAsignado(String motivoNoAsignado) {
		this.motivoNoAsignado = motivoNoAsignado;
	}

}