package com.slort.model;

// Generated by MyEclipse Persistence Tools

/**
 * HistoricoubicaciondetalleId generated by MyEclipse Persistence Tools
 */
public class HistoricoubicaciondetalleId extends
		AbstractHistoricoubicaciondetalleId implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public HistoricoubicaciondetalleId() {
	}

	/** full constructor */
	public HistoricoubicaciondetalleId(Calculoubicacion calculoubicacion,
			Flota flota) {
		super(calculoubicacion, flota);
	}

}
