package com.slort.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * Historicoubicaciondetalle generated by MyEclipse Persistence Tools
 */
public class Historicoubicaciondetalle extends
		AbstractHistoricoubicaciondetalle implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Historicoubicaciondetalle() {
	}

	/** minimal constructor */
	public Historicoubicaciondetalle(HistoricoubicaciondetalleId id) {
		super(id);
	}

	/** full constructor */
	public Historicoubicaciondetalle(HistoricoubicaciondetalleId id,
			Date fecha, Date hora, String gpsactivo, Integer ranking,
			String observaciones, Integer distanciaObjetivo,
			Date tiempoObjetivo, String motivoNoAsignado) {
		super(id, fecha, hora, gpsactivo, ranking, observaciones,
				distanciaObjetivo, tiempoObjetivo, motivoNoAsignado);
	}

}
