package com.slort.model;

import java.util.Date;

/**
 * AbstractReserva generated by MyEclipse Persistence Tools
 */

public abstract class AbstractReserva implements java.io.Serializable {

	// Fields

	private Integer idReserva;
	private Flota flota;
	private Hotel hotel;
	private Cliente cliente;
	private Usuario usuario;
	private Calculoubicacion calculoubicacion;
	private Date fecha;
	private Date hora;
	private String estado;
	private Integer idUsuario;
	private String observaciones;
	private String direccion;
	private String telefono;
	private String entreCalles;
	private String localidad;
	private Double latitud;
	private Double longitud;

	// Constructors

	/** default constructor */
	public AbstractReserva() {
	}

	/** minimal constructor */
	public AbstractReserva(Integer idReserva) {
		this.idReserva = idReserva;
	}

	/** full constructor */
	public AbstractReserva(Integer idReserva, Flota flota, Hotel hotel,
			Cliente cliente, Calculoubicacion calculoubicacion, Date fecha,
			Date hora, String estado, Integer idUsuario, String observaciones,
			String direccion, String telefono, String entreCalles,
			String localidad, Double latitud, Double longitud) {
		this.idReserva = idReserva;
		this.flota = flota;
		this.hotel = hotel;
		this.cliente = cliente;
		this.calculoubicacion = calculoubicacion;
		this.fecha = fecha;
		this.hora = hora;
		this.estado = estado;
		this.idUsuario = idUsuario;
		this.observaciones = observaciones;
		this.direccion = direccion;
		this.telefono = telefono;
		this.entreCalles = entreCalles;
		this.localidad = localidad;
		this.latitud = latitud;
		this.longitud = longitud;
	}

	// Property accessors

	public Integer getIdReserva() {
		return this.idReserva;
	}

	public void setIdReserva(Integer idReserva) {
		this.idReserva = idReserva;
	}

	public Flota getFlota() {
		return this.flota;
	}

	public void setFlota(Flota flota) {
		this.flota = flota;
	}

	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Calculoubicacion getCalculoubicacion() {
		return this.calculoubicacion;
	}

	public void setCalculoubicacion(Calculoubicacion calculoubicacion) {
		this.calculoubicacion = calculoubicacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getEntreCalles() {
		return this.entreCalles;
	}

	public void setEntreCalles(String entreCalles) {
		this.entreCalles = entreCalles;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}