package com.slort.model;

import java.util.Date;

/**
 * AbstractHistoricoubicaciondetalle generated by MyEclipse Persistence Tools
 */

public abstract class AbstractHistoricoubicaciondetalle implements
		java.io.Serializable {

	// Fields
	private Integer id;
	private Calculoubicacion calculoubicacion;
	private Flota flota;
	private Date fecha;
	private Date hora;
	private String gpsactivo;
	private Integer ranking;
	private String observaciones;
	private Float distanciaObjetivo;
	private String tiempoObjetivo;
	private String motivoNoAsignado;

	// Constructors

	/** default constructor */
	public AbstractHistoricoubicaciondetalle() {
	}

	/** minimal constructor */
	public AbstractHistoricoubicaciondetalle(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractHistoricoubicaciondetalle(Integer id, Calculoubicacion calculoubicacion,  Flota flota,
			Date fecha, Date hora, String gpsactivo, Integer ranking,
			String observaciones, Float distanciaObjetivo,
			String tiempoObjetivo, String motivoNoAsignado) {
		this.id = id;
		this.fecha = fecha;
		this.hora = hora;
		this.gpsactivo = gpsactivo;
		this.ranking = ranking;
		this.observaciones = observaciones;
		this.distanciaObjetivo = distanciaObjetivo;
		this.tiempoObjetivo = tiempoObjetivo;
		this.motivoNoAsignado = motivoNoAsignado;
		this.calculoubicacion = calculoubicacion;
	}

	// Property accessors


	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}



	public String getGpsactivo() {
		return this.gpsactivo;
	}

	public void setGpsactivo(String gpsactivo) {
		this.gpsactivo = gpsactivo;
	}

	public Integer getRanking() {
		return this.ranking;
	}

	public void setRanking(Integer ranking) {
		this.ranking = ranking;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}



	public Float getDistanciaObjetivo() {
		return distanciaObjetivo;
	}

	public void setDistanciaObjetivo(Float distanciaObjetivo) {
		this.distanciaObjetivo = distanciaObjetivo;
	}

	public String getTiempoObjetivo() {
		return tiempoObjetivo;
	}

	public void setTiempoObjetivo(String tiempoObjetivo) {
		this.tiempoObjetivo = tiempoObjetivo;
	}

	public String getMotivoNoAsignado() {
		return this.motivoNoAsignado;
	}

	public void setMotivoNoAsignado(String motivoNoAsignado) {
		this.motivoNoAsignado = motivoNoAsignado;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Flota getFlota() {
		return flota;
	}

	public void setFlota(Flota flota) {
		this.flota = flota;
	}

	public Date getHora() {
		return hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public Calculoubicacion getCalculoubicacion() {
		return calculoubicacion;
	}

	public void setCalculoubicacion(Calculoubicacion calculoubicacion) {
		this.calculoubicacion = calculoubicacion;
	}

}