package com.slort.model;

/**
 * AbstractConexion generated by MyEclipse Persistence Tools
 */

public abstract class AbstractConexion implements java.io.Serializable {

	// Fields

	private Integer idConexion;
	private String ambiente;
	private String nombre;
	private String driver;
	private String url;
	private String usuario;
	private String password;

	// Constructors

	/** default constructor */
	public AbstractConexion() {
	}

	/** minimal constructor */
	public AbstractConexion(Integer idConexion) {
		this.idConexion = idConexion;
	}

	/** full constructor */
	public AbstractConexion(Integer idConexion, String ambiente, String nombre,
			String driver, String url, String usuario, String password) {
		this.idConexion = idConexion;
		this.ambiente = ambiente;
		this.nombre = nombre;
		this.driver = driver;
		this.url = url;
		this.usuario = usuario;
		this.password = password;
	}

	// Property accessors

	public Integer getIdConexion() {
		return this.idConexion;
	}

	public void setIdConexion(Integer idConexion) {
		this.idConexion = idConexion;
	}

	public String getAmbiente() {
		return this.ambiente;
	}

	public void setAmbiente(String ambiente) {
		this.ambiente = ambiente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDriver() {
		return this.driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}