package com.slort.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;

/**
 * Cliente generated by MyEclipse Persistence Tools
 */
public class Cliente extends AbstractCliente implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Cliente() {
	}

	/** minimal constructor */
	public Cliente(Integer codCliente) {
		super(codCliente);
	}

	/** full constructor */
	public Cliente(Integer codCliente, String tipoCliente, String nombre,
			String apellido, String razonsocial, String domicilio,
			String codPostal, String localidad, String telefono, String cargo,
			String email, Date fechaAlta, Date fechaBaja, String tipoDocu,
			String numDoc, String estado, Date fechaModif, Byte fleliminado,
			Set reservas) {
		super(codCliente, tipoCliente, nombre, apellido, razonsocial,
				domicilio, codPostal, localidad, telefono, cargo, email,
				fechaAlta, fechaBaja, tipoDocu, numDoc, estado, fechaModif,
				fleliminado, reservas);
	}

}
