package com.slort.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;

/**
 * Flota generated by MyEclipse Persistence Tools
 */
public class Flota extends AbstractFlota implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Flota() {
	}

	/** minimal constructor */
	public Flota(Integer codUnidad) {
		super(codUnidad);
	}

	/** full constructor */
	public Flota(Integer codUnidad, Byte activo, String userYahoo,
			String passwYahoo, String nombre, String apellido,
			String domicilio, String codPostal, String localidad,
			String telefono, String cargo, String email, Date fechaAlta,
			Date fechaBaja, String cuit, String licencia, Date fechaModif,
			Byte fleliminado, Set reservas, Set ubicacionreals,
			Set historicoubicaciondetalles,String consumerKeyYahoo,String consumerSecretYahoo) {
		super(codUnidad, activo, userYahoo, passwYahoo, nombre, apellido,
				domicilio, codPostal, localidad, telefono, cargo, email,
				fechaAlta, fechaBaja, cuit, licencia, fechaModif, fleliminado,
				reservas, ubicacionreals, historicoubicaciondetalles,consumerKeyYahoo,consumerSecretYahoo);
	}

}
