package com.slort.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * Historicoubicaciondetalle generated by MyEclipse Persistence Tools
 */
public class Historicoubicaciondetalle extends
		AbstractHistoricoubicaciondetalle implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Historicoubicaciondetalle() {
	}

	/** minimal constructor */
	public Historicoubicaciondetalle(Integer id) {
		super(id);
	}

	/** full constructor */
	public Historicoubicaciondetalle(Integer id, Calculoubicacion  calculoubicacion , Flota flota,
			Date fecha, Date hora, String gpsactivo, Integer ranking,
			String observaciones, Float distanciaObjetivo,
			String tiempoObjetivo, String motivoNoAsignado) {
		super(id,  calculoubicacion , flota, fecha, hora, gpsactivo, ranking, observaciones,
				distanciaObjetivo, tiempoObjetivo, motivoNoAsignado);
	}

}
